CREATE TABLE ordenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente BIGINT,
    metodo_pago VARCHAR(20),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    estado VARCHAR(20) NOT NULL DEFAULT 'CARRITO',
    total NUMERIC(10,2),
    PRIMARY KEY (id)
);

CREATE TABLE orden_detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_orden BIGINT NOT NULL REFERENCES ordenes(id),
    id_producto BIGINT NOT NULL,
    nombre_producto VARCHAR(150),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2),
    PRIMARY KEY (id)
);